apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-deploy-1
spec:
  template:
    metadata:
      labels:
        app: my-deploy-1
    spec:
      containers:
        - name: my-deploy-1
          image: nginx
          ports:
            - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: my-deploy-1
  strategy:
    type: rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
