apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: xyz-app
spec:
  template:
    metadata:
      labels:
        app: xyz-app
    spec:
      containers:
        - name: xyz-app
          image: nginx
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: xyz-app
  strategy:
    type: RollingUpdate








apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: my-deploy
  namespace: ns-demo
spec:
  template:
    metadata:
      labels:
        app: my-deploy
      namespace: ns-demo
    spec:
      containers:
        - name: my-deploy
          image: nginx
          ports:
            - name: nginx
              containerPort: 80
              protocol: TCP
    replicas: 3
    selector:
      matchLabels:
    strategy:
      type: RollingUpdate






