apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: my-app
  apiVersion: v1
  kind: Namespace
  metadata:
    name:  name
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80