apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
  namespaces: ns1
spec:
  containers:
    - name: my-app
      image: nginx
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
