apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc-1
  labels: 
    app: my-rc-1
spec:
  template:
    metadata:
      labels: 
        app: my-pod-1
    spec:
      containers:
        - name: my-pod-1
          image: httpd
          ports:
          - name:  Port Name
            port:  Port
            protocol: TCP
      