apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs-1
  labels:
    app: my-rs-1
spec:
  template:
    metadata:
      labels:
        app: my-rs-1
    spec:
      containers:
        - name: my-rs-1
          image: nginx
          ports:
            - name: nginx
              containerPort: 80
              protocol: TCP
    replicas: 2
    selector:
      matchLabels:
        app: my-rs-1
