apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs-1
  labels:
    app: my-rs-1
spec: 
  template:
    metadata:
      labels:
        app: my-rs-1
    spec:
      containers:
      - name: my-po
        image: nginx
        ports:
          - name: http
            protocol: TCP
            containerPort: 80
  replicas: 3
  selector:
    # matchLabels:
    #   app: cbz-app