apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs-1
  labels:
    app: my-rs-1
spec:
  template:
    metadata:
      labels:
        app: my-rs-1
      namespace: ns-demo
    spec:
      containers:
        - name: my-pod-1
          image: httpd
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
  replicas: 0
  selector:
    matchLabels:
      app: my-rs-1
