apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: my-rs-1
  labels:
    app: my-rs-1
spec:
  template:
    metadata:
      labels:
        app: my-pod-2
    spec:
      containers:
        - name: my-pod-2
          image:  nginx
          ports:
          - name:  Port Name
            containerPort: 80
            protocol: TCP