apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs-1
  labels:
    app: my-rs-1
spec:
  template:
    metadata:
      labels:
        app: my-rs-1
    spec:
      containers:
        - name: my-pod-2
          image: nginx
          ports:
            - name: nginx
              containerPort: 80
              protocol: TCP
    replicas: 2
    selector:
      matchLabels:
        app: my-rs-1


apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels:
    app: cbz-app
spec: 
  template:
    metadata:
      labels:
        app: cbz-app
    spec:
      containers:
      - name: my-app
        image: nginx
        ports:
          - name: http
            protocol: TCP
            containerPort: 80
  replicas: 3
  selector:
    # matchLabels:
    #   app: cbz-app