apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: frontend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376

  selector:
    app: my-pod-1