# apiVersion: v1
# kind: Service
# metadata:
#   name: my-app-svc
#   namespace: frontend
# spec:
#   type: NodePort
#   ports:
#     - name: http
#       port: 80
#       targetPort: 80
#       protocol: TCP
#   selector:
#     my: my-app
# 
apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
  namespace: frontend
spec:
  containers:
    - name: my-app
      image: nginx
      ports:
        - name: http
          protocol: TCP
          containerPort: 80


apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: my-app