apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
  namespace: frontend
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    my: my-app
